repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 25.1.0 # Using a more recent version of black
    hooks:
      - id: black
        language_version: python3.12
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13 # Using a more recent version of ruff
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix, --ignore=F405, F403]
      # Run the formatter (replaces isort)
      - id: ruff-format
